export const EnglishLocale = {
    0: 'No available virtual cards found',
    1: 'File is empty',
    2: 'File has incorrect format. Encountered row: ',
    3: 'Region not found',
    4: 'Category not found with id {value0}',
    5: 'Station not found',
    6: 'Store was not found with id ',
    7: 'Good was not found',
    8: 'User is not authorized in manzana',
    9: 'Order was not found with id ',
    10: 'Client does not have current order with id ',
    11: 'PayType is not supported: ',
    12: 'no authorized payment with this id ',
    13: 'Status was not found with id ',
    14: 'No SBOL account found with this store`s INN',
    15: 'Prices cannot be counted for the next goods: ',
    16: 'Cannot reverse order with statuses "Продан" and "На дефектуре"',
    17: 'Cannot get prices for goods. Wrong "storeId" or "goodsIds" are defined.'
}
