export const NODE_ENV = process.env.NODE_ENV || 'development'
export const PORT = process.env.PORT || '1340'
export const ECOM_URL = process.env.ECOM_URL || 'http://ws.erkapharm.com:8990/ecom/hs/'
export const ECOM_USER = process.env.ECOM_USER || 'IdEast'
export const ECOM_PASS = process.env.ECOM_PASS || 'KZMY5N'
export const MONGO_URI = process.env.MONGO_HOST || 'mongodb://localhost:27017'
export const MONGO_DB = process.env.MONGO_DB || 'xcom-prod'

// 'http://ws.erkapharm.com:8990/ecom/hs/'
// 'http://ws-dev.erkapharm.com:8990/ecom_test/hs'
